name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tg2alexa:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Run tests
      run: |
        pip install -r tests/requirements.txt
        pytest tests/
        
    - name: Notify deployment
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"text":"New tg2alexa image built and pushed"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}